(function () {
  'use strict';
  function text(value) { return typeof value === 'string' ? value.trim() : ''; }
  function list(value) { return Array.isArray(value) ? value.filter(function (item) { return text(item); }) : []; }
  function escapeHtml(value) { return String(value == null ? '' : value).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;').replace(/'/g, '&#039;'); }
  function humanLabel(value) { return text(value).replace(/\b[a-z]/g, function (letter) { return letter.toUpperCase(); }); }
  function signalOf(entry) { return entry && entry.signal ? entry.signal : entry; }
  function pair(signal, heading, en, zh) { if (!text(signal[en]) && !text(signal[zh])) return ''; return '<section class="archive-detail-block archive-primary"><h2>' + heading + '</h2>' + (text(signal[en]) ? '<p>' + escapeHtml(signal[en]) + '</p>' : '') + (text(signal[zh]) ? '<p class="archive-zh-body">' + escapeHtml(signal[zh]) + '</p>' : '') + '</section>'; }
  function related(values, archive) { if (!values.length) return ''; return '<section class="archive-detail-block"><h2>RELATED SIGNALS</h2><ul class="archive-detail-list">' + values.map(function (value) { var entry = archive.index.byId[value] || archive.index.catalogEntries.find(function (item) { return archive.normalizeTerm(item.signal.term) === archive.normalizeTerm(value); }); var signal = signalOf(entry); return '<li>' + (signal ? '<a href="./archive-signal.html?id=' + encodeURIComponent(signal.id) + '">' + escapeHtml(humanLabel(signal.displayTerm || signal.term)) + '</a>' : escapeHtml(value)) + '</li>'; }).join('') + '</ul></section>'; }
  function variants(group) { if (!group || group.variants.length < 2) return ''; return '<details class="archive-detail-block archive-disclosure wide"><summary>ARCHIVE RECORDS</summary><div class="archive-variant-list">' + group.variants.map(function (entry) { var signal = entry.signal; return '<a href="./archive-signal.html?id=' + encodeURIComponent(signal.id) + '"><strong>' + escapeHtml(signal.displayTerm || signal.term) + '</strong><span>' + escapeHtml(entry.status === 'available' ? 'Available in ' + ((entry.pack && entry.pack.name) || 'Content Pack') : 'Active') + '</span></a>'; }).join('') + '</div></details>'; }
  function render(entry, archive) { var signal = signalOf(entry); if (!signal) return '<section class="archive-detail-block wide"><h2>RECORD NOT FOUND</h2><p>This identifier is not in the current Signal Registry.</p></section>'; var group = archive.findGroup(signal.id, 'catalog'); return pair(signal, 'MEANING', 'meaningEn', 'meaningZh') + pair(signal, 'CULTURAL CONTEXT', 'culturalContextEn', 'culturalContextZh') + pair(signal, 'EXAMPLE', 'exampleEn', 'exampleZh') + '<details class="archive-detail-block archive-disclosure wide"><summary>DEEP DIVE</summary>' + pair(signal, 'ORIGINAL MEANING', 'originalMeaningEn', 'originalMeaningZh') + related(list(signal.relatedTerms), archive) + '</details>' + variants(group) + '<details class="archive-detail-block archive-disclosure wide"><summary>RECORD INFO</summary><dl class="archive-record-info"><div><dt>Signal ID</dt><dd>' + escapeHtml(signal.id) + '</dd></div><div><dt>Source</dt><dd>' + escapeHtml(signal.sourceName || signal.sourceType || 'English Radar registry') + '</dd></div><div><dt>Category</dt><dd>' + escapeHtml(signal.category) + '</dd></div></dl></details>'; }
  function boot() { var archive = window.EnglishRadarArchive; var entry = archive && archive.findSignal ? archive.findSignal(new URLSearchParams(window.location.search).get('id') || '') : null; var signal = signalOf(entry); var title = document.querySelector('[data-archive-detail-title]'); var type = document.querySelector('[data-archive-detail-type]'); var note = document.querySelector('[data-archive-detail-term-note]'); var chips = document.querySelector('[data-archive-detail-chips]'); var availability = document.querySelector('[data-archive-detail-availability]'); var actions = document.querySelector('[data-archive-detail-actions]'); var content = document.querySelector('[data-archive-detail-content]'); if (title) title.textContent = signal ? (signal.displayTerm || signal.term) : 'UNKNOWN RECORD'; if (type) type.textContent = signal ? archive.recordType(signal) : 'ARCHIVE ERROR'; if (note) note.textContent = signal ? ((signal.pronunciation || signal.ipa || '') + (signal.category ? ' · ' + signal.category : '')) : ''; if (chips && signal) chips.innerHTML = list(signal.platforms).concat(list(signal.tone)).map(function (value) { return '<span class="archive-chip">' + escapeHtml(value) + '</span>'; }).join(''); var active = !entry || entry.status === 'active'; if (availability) availability.innerHTML = signal ? (active ? '<span class="archive-active-badge">ACTIVE / 已激活</span>' : '<span class="archive-availability">AVAILABLE IN ' + escapeHtml(entry.pack && entry.pack.name || 'CONTENT PACK') + '<small>NOT INSTALLED / 未安装</small></span>') : ''; if (actions) actions.innerHTML = signal ? (active ? '<a class="archive-cta" href="./learn.html?mode=lookup&signal=' + encodeURIComponent(signal.id) + '">Learn this Signal / 学习这个表达</a>' : '<a class="archive-cta" href="./me.html#content-library">View Content Pack / 查看内容包</a>') : ''; if (content) content.innerHTML = render(entry, archive); }
  window.EnglishRadarArchiveDetail = { render: render };
  document.addEventListener('DOMContentLoaded', boot);
}());
