const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');
const root = path.resolve(__dirname, '..');
const read = (file) => fs.readFileSync(path.join(root, file), 'utf8');
const context = { window: {}, document: { addEventListener() {} }, console, Date, Object, Array, String, Number, Math, URLSearchParams };
vm.createContext(context);
['js/bundled-pack-registry.js', 'data/signals.js', 'data/content-pack-01.js', 'data/content-pack-02.js', 'data/content-pack-03.js', 'data/content-pack-04.js', 'data/content-pack-05.js', 'js/content-registry.js', 'js/archive.js', 'js/archive-signal.js'].forEach((file) => vm.runInContext(read(file), context, { filename: file }));
const archive = context.window.EnglishRadarArchive;
const index = archive.createIndex(context.window.EnglishRadarContent, context.window.EnglishRadarBundledPackRegistry);
assert(index.activeGroups.length >= 50);
assert(index.catalogGroups.length >= index.activeGroups.length);
assert(index.catalogGroups.find((group) => group.key === 'touch grass').variants.length >= 2);
assert.equal(archive.searchIndex(index, 'Library', 'all', 'my').length, 0);
const library = archive.searchIndex(index, 'Library', 'all', 'catalog')[0];
assert.equal(library.primary.signal.id, 'pn-library');
assert.equal(library.primary.status, 'available');
assert.equal(archive.searchIndex(index, 'touch grass', 'all', 'catalog').length, 1);
assert(read('archive.html').includes('data-archive-scope="my"'));
assert(read('archive.html').includes('data-archive-scope="catalog"'));
assert(read('archive-signal.html').includes('data-archive-detail-actions'));
assert(read('js/archive.js').includes('NOT INSTALLED'));
assert(!/localStorage|setItem|removeItem/.test(read('js/archive.js')));
console.log('PASS: formal Archive catalog visibility, grouping and non-persistent scope checks');
