const assert = require('assert');
const fs = require('fs');
const path = require('path');
const vm = require('vm');

const root = path.resolve(__dirname, '..');
const read = file => fs.readFileSync(path.join(root, file), 'utf8');
const context = { window: {}, console, document: { addEventListener() {} } };
vm.createContext(context);
['js/bundled-pack-registry.js', 'data/signals.js', 'data/content-pack-01.js', 'data/content-pack-02.js', 'data/content-pack-03.js', 'data/content-pack-04.js', 'data/content-pack-05.js', 'js/content-registry.js', 'js/archive.js'].forEach(file => vm.runInContext(read(file), context, { filename: file }));
const archive = context.window.EnglishRadarArchive;
const content = { getDictionarySignals: () => context.window.ENGLISH_RADAR_SIGNALS, normalizeSignal: signal => signal };
const index = archive.createIndex(content, context.window.EnglishRadarBundledPackRegistry);
assert.match(read('archive.html'), /Personal Internet Context Archive/);
for (const label of ['Internet Culture', 'Developer Language', 'Product Language', 'Community Expression', 'Saved Signals']) assert.match(read('archive.html'), new RegExp(label));
assert.match(read('archive.html'), /growing library of internet expressions/i);
assert.match(read('js/archive.js'), /masteryLabel/);
assert.match(read('js/archive.js'), /metadataText/);
assert.ok(!/radarArchive|archiveSignals|contextArchive/.test(read('js/archive.js')));
assert.equal(archive.masteryLabel({ id: 'x' }, {}), 'New');
assert.equal(archive.masteryLabel({ id: 'x' }, { x: { mastery: 'fuzzy' } }), 'Familiar');
assert.equal(archive.masteryLabel({ id: 'x' }, { x: { mastery: 'clear' } }), 'Clear');
assert.ok(archive.searchIndex(index, 'engineering', 'all', 'catalog').length > 0, 'context keywords should be searchable');
assert.ok(archive.searchIndex(index, '', 'Internet Culture', 'catalog').length > 0);
assert.ok(archive.searchIndex(index, '', 'Developer Language', 'catalog').length > 0);
assert.ok(archive.searchIndex(index, '', 'Product Language', 'catalog').length > 0);
assert.ok(archive.searchIndex(index, '', 'Community Expression', 'catalog').length > 0);
assert.ok(archive.searchIndex(index, '', 'saved', 'catalog', { 'internet-lowkey': { favorite: true } }).some(group => group.variants.some(entry => entry.signal.id === 'internet-lowkey')));
assert.deepEqual(Object.keys(context.window.EnglishRadarStorage || {}), []);
console.log('v0.1 archive foundation tests: PASS');
