const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');

const root = path.resolve(__dirname, '..');
const read = (file) => fs.readFileSync(path.join(root, file), 'utf8');
const context = vm.createContext({ window: { ENGLISH_RADAR_SIGNALS: [], location: { search: '?feed=daily-mix' } }, console, Date, Intl, Math, Number, String, Array, Object, URLSearchParams });
vm.runInContext(read('data/signals.js'), context);
const storage = { getCustomSignals: () => ({ version: 1, packs: [{ id: 'english-radar-ui-vocabulary-core' }], signals: Object.fromEntries(context.window.ENGLISH_RADAR_UI_VOCABULARY_PACK.signals.map((signal) => [signal.id, signal])) }), getInbox: () => [], getProgress: () => ({}) };
context.window.EnglishRadarStorage = storage;
vm.runInContext(read('data/ui-vocabulary-core-pack.js'), context);
vm.runInContext(read('data/quizzes.js'), context);
vm.runInContext(read('data/ui-vocabulary-quizzes.js'), context);
vm.runInContext(read('js/quiz-registry.js'), context);
vm.runInContext(read('js/content-registry.js'), context);
vm.runInContext(read('js/learning-engine.js'), context);
const engine = context.window.EnglishRadarLearningEngine;
const mix = engine.getDailyMix();
assert.equal(mix.length, 5);
assert.equal(new Set(mix.map((signal) => signal.id)).size, 5);
assert.ok(mix.filter((signal) => signal.radarType === 'interface').length <= 1);
assert.ok(mix.some((signal) => signal.radarType === 'interface'));
assert.deepEqual(engine.getDailyMix().map((signal) => signal.id), mix.map((signal) => signal.id));
assert.equal(context.window.EnglishRadarQuizRegistry.getInterfaceQuizzes().filter((question) => ['ui-daily-mix', 'ui-dictionary', 'ui-inbox', 'ui-profile', 'ui-quiz'].includes(question.signalId)).length, 10);
const source = read('js/dictionary.js');
['productMeaningEn', 'productMeaningZh', 'originalMeaningEn', 'originalMeaningZh', 'commonInterfaces', 'confusedWith'].forEach((field) => assert(source.includes(field), `Dictionary search should include ${field}`));
const quizSource = read('js/quiz.js');
assert(quizSource.includes("mode === 'interface'"));
assert(quizSource.includes('getInterfaceQuizzes'));
assert(quizSource.includes('data-interface-install-link'));
assert(read('js/imported-quiz-generator.js').includes("radarType !== 'interface'"));
const sessionSource = read('js/session.js');
assert(sessionSource.includes('EnglishRadarQuizRegistry'));
assert(sessionSource.includes('signal.quizStatus !== \'none\''));
const review = vm.createContext({ window: {} });
vm.runInContext(read('js/review.js'), review);
const uiProgress = { 'ui-review': { signalId: 'ui-review', firstLearnedAt: '2026-07-01T00:00:00.000Z', lastReviewedAt: '2026-07-01T00:00:00.000Z', nextReviewAt: '2026-07-02T00:00:00.000Z', mastery: 'new' } };
assert.equal(review.window.EnglishRadarReview.getReviewQueue([{ id: 'ui-review' }], uiProgress, new Date('2026-08-01T00:00:00.000Z')).length, 1);
console.log('PASS: V1.2 UI Vocabulary learning-loop integration checks');
