const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');
const root = path.resolve(__dirname, '..');
const read = (file) => fs.readFileSync(path.join(root, file), 'utf8');
const pages = ['index.html', 'learn.html', 'dictionary.html', 'archive.html', 'archive-signal.html', 'quiz.html', 'inbox.html', 'me.html', '404.html'];
for (const page of pages) assert(read(page).includes('v1.8.1'), `${page} should expose v1.8.1 metadata`);
 for (const page of ['index.html', 'learn.html', 'dictionary.html', 'quiz.html', 'inbox.html', 'me.html']) { const html = read(page); assert(html.includes('formal-nav.js?v=1.8.1'), `${page} should load formal navigation`); assert((html.match(/class="nav-item/g) || []).length >= 5); assert.equal((html.match(/class="mobile-nav/g) || []).length, 1); assert(!html.includes('class="mobile-nav" aria-label="Mobile navigation"><a href="./inbox.html"'), `${page} mobile nav should omit Inbox`); }
assert(read('index.html').includes('Open Inbox'));
assert(read('learn.html').includes('data-archive-secondary-link'));
assert(!read('dictionary.html').includes('archive-secondary-link'));
assert(read('archive.html').includes('id="main-content"') && read('archive.html').includes('v=1.8.0'));
assert(read('archive-signal.html').includes('data-archive-detail-actions') && read('archive-signal.html').includes('id="main-content"'));
assert(read('js/archive-signal.js').includes('./me.html#content-library'));
assert(!/localStorage|setItem|removeItem/.test(read('js/archive.js')));
const context = { window: {}, document: { addEventListener() {} }, console, Date, Object, Array, String, Number, Math, URLSearchParams };
vm.createContext(context);
['js/bundled-pack-registry.js', 'data/signals.js', 'data/content-pack-01.js', 'data/content-pack-02.js', 'data/content-pack-03.js', 'data/content-pack-04.js', 'data/content-pack-05.js', 'js/content-registry.js', 'js/archive.js'].forEach((file) => vm.runInContext(read(file), context, { filename: file }));
const archive = context.window.EnglishRadarArchive;
const index = archive.createIndex(context.window.EnglishRadarContent, context.window.EnglishRadarBundledPackRegistry);
assert(index.catalogGroups.length > index.activeGroups.length);
assert.equal(archive.searchIndex(index, 'Library', 'all', 'my').length, 0);
const available = archive.searchIndex(index, 'Library', 'all', 'catalog')[0].primary;
assert.equal(available.status, 'available');
assert.equal(available.pack.id, 'english-radar-content-pack-05');
assert.equal(archive.searchIndex(index, 'touch grass', 'all', 'catalog').length, 1);
assert(read('js/archive-signal.js').includes('View Content Pack'));
console.log('PASS: v1.8 Archive Mode visibility, routing, navigation, metadata and lifecycle boundaries');
